const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { parseAdif, bandToCanonical, normMode, toTimestamp } = require('../../src/analyze/adif');

const ADI = `Generated by N1MM
<ADIF_VER:5>3.1.4
<PROGRAMID:4>N1MM
<EOH>
<CALL:4>K3LR <QSO_DATE:8>20250524 <TIME_ON:6>120000 <BAND:3>20m <MODE:2>CW <OPERATOR:4>WT2P <STATION_CALLSIGN:4>WT2P <CONT:2>NA <CQZ:1>5 <APP_N1MM_POINTS:1>2 <APP_N1MM_ISMULTIPLIER1:1>1 <APP_N1MM_ISRUNQSO:1>1 <CONTEST_ID:9>CQ-WPX-CW <EOR>
<CALL:6>DL1XYZ <QSO_DATE:8>20250524 <TIME_ON:6>120100 <BAND:3>20m <MODE:2>CW <OPERATOR:4>WT2P <CONT:2>EU <CQZ:2>14 <APP_N1MM_POINTS:1>3 <APP_N1MM_ISMULTIPLIER1:1>0 <APP_N1MM_ISRUNQSO:1>0 <EOR>
<CALL:6>JA1ABC <QSO_DATE:8>20250524 <TIME_ON:4>1305 <BAND:3>40m <MODE:3>SSB <OPERATOR:4>K3LR <APP_N1MM_POINTS:1>3 <APP_N1MM_ISMULTIPLIER1:1>1 <APP_N1MM_ISRUNQSO:1>0 <EOR>
`;

describe('parseAdif', () => {
  const { meta, qsos, flags } = parseAdif(ADI);

  it('skips the header and parses each record', () => {
    assert.equal(qsos.length, 3);
    assert.deepEqual(qsos.map((q) => q.call), ['K3LR', 'DL1XYZ', 'JA1ABC']);
  });

  it('carries the N1MM app fields and sets the flags', () => {
    assert.equal(flags.has_points, true);
    assert.equal(flags.has_mults, true);
    assert.equal(flags.has_operator, true);
    assert.equal(flags.has_run_flag, true);
    assert.equal(qsos[0].points, 2);
    assert.equal(qsos[0].is_mult1, 1);
    assert.equal(qsos[0].is_run_qso, 1);
    assert.equal(qsos[1].is_run_qso, 0);
    assert.equal(qsos[0].operator, 'WT2P');
    assert.equal(qsos[2].operator, 'K3LR');
  });

  it('takes continent / zone straight from the file', () => {
    assert.equal(qsos[0].continent, 'NA');
    assert.equal(qsos[0].zone, '5');
    assert.equal(qsos[1].zone, '14');
  });

  it('canonicalises BAND to the same value space as Cabrillo', () => {
    assert.equal(qsos[0].band, '14');
    assert.equal(qsos[2].band, '7');
  });

  it('builds timestamps from HHMMSS or HHMM', () => {
    assert.equal(qsos[0].n1mm_timestamp, '2025-05-24 12:00:00');
    assert.equal(qsos[2].n1mm_timestamp, '2025-05-24 13:05:00');
  });

  it('reads contest id and station call into meta', () => {
    assert.equal(meta.contest, 'CQ-WPX-CW');
    assert.equal(meta.station_call, 'WT2P');
    assert.ok(meta.operators.includes('WT2P'));
    assert.ok(meta.operators.includes('K3LR'));
  });

  it('a log with no N1MM app fields flags them all false', () => {
    const plain = '<EOH>\n<CALL:4>K3LR<QSO_DATE:8>20250524<TIME_ON:4>1200<BAND:3>20m<MODE:2>CW<EOR>\n';
    const r = parseAdif(plain);
    assert.equal(r.qsos.length, 1);
    assert.equal(r.flags.has_points, false);
    assert.equal(r.flags.has_operator, false);
  });

  it('parses even with no header at all', () => {
    const r = parseAdif('<CALL:4>K3LR<QSO_DATE:8>20250524<TIME_ON:4>1200<BAND:3>20m<MODE:2>CW<EOR>');
    assert.equal(r.qsos.length, 1);
  });

  it('marks APP_N1MM_ISCLAIMEDQSO=0 as excluded (ADIF X-QSO equivalent)', () => {
    const adi = '<EOH>\n'
      + '<CALL:4>K3LR<QSO_DATE:8>20250524<TIME_ON:4>1200<BAND:3>20m<MODE:2>CW<APP_N1MM_ISCLAIMEDQSO:1>1<EOR>\n'
      + '<CALL:6>N0DUPE<QSO_DATE:8>20250524<TIME_ON:4>1201<BAND:3>20m<MODE:2>CW<APP_N1MM_ISCLAIMEDQSO:1>0<EOR>\n';
    const r = parseAdif(adi);
    assert.equal(r.qsos.length, 2);
    assert.equal(r.qsos[0].excluded, 0);
    assert.equal(r.qsos[1].excluded, 1);
  });

  it('helpers', () => {
    assert.equal(bandToCanonical('20m', ''), '14');
    assert.equal(bandToCanonical('', '14.025'), '14');
    assert.equal(normMode('USB'), 'SSB');
    assert.equal(normMode('MFSK', 'FT4'), 'FT4');
    assert.equal(toTimestamp('20250524', '1305'), '2025-05-24 13:05:00');
  });
});
